# Generated by Django 5.2.7 on 2025-10-30 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActaPartido',
            fields=[
                ('id_acta', models.AutoField(primary_key=True, serialize=False)),
                ('sancion', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_encuentro', models.DateField(blank=True, null=True)),
                ('incidentes', models.TextField(blank=True, null=True)),
                ('resultado', models.CharField(blank=True, max_length=20, null=True)),
                ('digitov', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'acta_partido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Anuncio',
            fields=[
                ('id_anuncio', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_publicacion', models.DateTimeField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('digitov', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'anuncio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cancha',
            fields=[
                ('id_cancha', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('superficie', models.CharField(blank=True, max_length=20, null=True)),
                ('disponibilidad', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'cancha',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CargoArbitral',
            fields=[
                ('id_cargo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_cargo', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'cargo_arbitral',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id_club', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('contacto', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'club',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ClubSerie',
            fields=[
                ('id_club_serie', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicio', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'club_serie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('provincia', models.CharField(blank=True, max_length=50, null=True)),
                ('codigo_postal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comunas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CuerpoArbitral',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_partidos', models.IntegerField(blank=True, null=True)),
                ('cantidad_tarjetas', models.IntegerField(blank=True, null=True)),
                ('funcion_arb', models.CharField(blank=True, max_length=50, null=True)),
                ('cursos', models.TextField(blank=True, null=True)),
                ('digitov', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'cuerpo_arbitral',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id_documento', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_documento', models.CharField(blank=True, max_length=50, null=True)),
                ('archivo', models.TextField(blank=True, null=True)),
                ('fecha_subida', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'documento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id_estado', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_estado', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'estado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoActa',
            fields=[
                ('id_estado_acta', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'estado_acta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('rut_jugador', models.IntegerField(primary_key=True, serialize=False)),
                ('digitov', models.CharField(max_length=1)),
                ('nombre', models.CharField(blank=True, max_length=30, null=True)),
                ('apellido', models.CharField(blank=True, max_length=30, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(blank=True, max_length=30, null=True)),
                ('num_camiseta', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'jugadores',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='JugadorPartido',
            fields=[
                ('pk', models.CompositePrimaryKey('id_jugador', 'id_partido', blank=True, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'jugador_partido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ligas',
            fields=[
                ('id_liga', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('temporada', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'ligas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.IntegerField()),
                ('digitov', models.CharField(max_length=1)),
                ('contrasena', models.CharField(max_length=100)),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_logueo', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'login',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id_pago', models.AutoField(primary_key=True, serialize=False)),
                ('monto', models.IntegerField()),
                ('estado', models.CharField(blank=True, max_length=20, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('digitov', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'pagos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Partidos',
            fields=[
                ('id_partido', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('hora', models.TimeField(blank=True, null=True)),
                ('club_local', models.CharField(blank=True, max_length=50, null=True)),
                ('club_visitante', models.CharField(blank=True, max_length=50, null=True)),
                ('resultado', models.CharField(blank=True, max_length=10, null=True)),
                ('estado', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'partidos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reglamento',
            fields=[
                ('id_reglamento', models.AutoField(primary_key=True, serialize=False)),
                ('reglas', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(blank=True, null=True)),
                ('fecha_vigencia', models.DateField(blank=True, null=True)),
                ('fecha_termino', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
                ('digitov', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'reglamento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('rol_id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sanciones',
            fields=[
                ('id_sancion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_inc', models.DateField(blank=True, null=True)),
                ('motivo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sanciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id_serie', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'serie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tablaposiciones',
            fields=[
                ('id_tabla', models.AutoField(primary_key=True, serialize=False)),
                ('pa_jugados', models.IntegerField(blank=True, null=True)),
                ('pa_ganados', models.IntegerField(blank=True, null=True)),
                ('pa_perdidos', models.IntegerField(blank=True, null=True)),
                ('pa_empatados', models.IntegerField(blank=True, null=True)),
                ('goles_favor', models.IntegerField(blank=True, null=True)),
                ('goles_contra', models.IntegerField(blank=True, null=True)),
                ('puntos', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tablaposiciones',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id_tipo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_metodo_pago', models.CharField(blank=True, max_length=100, null=True)),
                ('detalle', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'tipo_pago',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id_torneo', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=100, null=True)),
                ('temporada', models.CharField(blank=True, max_length=50, null=True)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('fec_inicio', models.DateField(blank=True, null=True)),
                ('fec_fin', models.DateField(blank=True, null=True)),
                ('fixture', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'torneo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rut', models.IntegerField(primary_key=True, serialize=False)),
                ('digitov', models.CharField(max_length=1)),
                ('nombre', models.CharField(max_length=50)),
                ('apellidop', models.CharField(max_length=50)),
                ('apellidom', models.CharField(max_length=50)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('correo', models.CharField(max_length=150, unique=True)),
                ('direccion', models.CharField(blank=True, max_length=50, null=True)),
                ('fecharegistro', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuarioRol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_asignacion', models.DateField(blank=True, null=True)),
                ('digitov', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'usuarios_roles',
                'managed': False,
            },
        ),
    ]
